version: "3.8"

# set-up networks
networks:
  private-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.102.0/24
          gateway: 172.20.102.1
    internal: true

  public-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.102.0/24
          gateway: 172.16.102.1
    internal: false

  Internet:
    driver: bridge

# set-up services
services:
  # set-up nginx for the web server
  server:
    container_name: "nginx-server"
    build:
      context: .
      dockerfile: ./dockerfiles/nginx.Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - database
    networks:
      private-net:
        ipv4_address: 172.20.102.2
      public-net:
        ipv4_address: 172.16.102.2

  # set-up php
  php:
    container_name: "php-server"
    build:
      context: .
      dockerfile: ./dockerfiles/php.Dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      private-net:
        ipv4_address: 172.20.102.3
      Internet:

  # set-up database with postgres
  database:
    container_name: "database-server"
    image: postgres:13-alpine
    restart: on-failure
    env_file:
      - ./.env/pg.env
    ports:
      - "5432"
    networks:
      private-net:
        ipv4_address: 172.20.102.4

  # set-up composer for the laravel
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      public-net:
        ipv4_address: 172.16.102.3

  # set-up artisan for the laravel
  artisan:
    build:
      context: .
      dockerfile: ./dockerfiles/php.Dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      private-net:
        ipv4_address: 172.20.102.5

  # set-up redis for the laravel
  redis:
    container_name: "redis-server"
    build:
      context: .
      dockerfile: ./dockerfiles/redis.Dockerfile
    ports:
      - "6379"
    networks:
      private-net:
        ipv4_address: 172.20.102.6

  # set-up pgAdmin for PostgreSQL management
  adminer:
    container_name: "adminer-server"
    image: adminer
    restart: always
    networks:
      private-net:
        ipv4_address: 172.20.102.7

  redis-commander:
    container_name: "redis-commander-server"
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - ./.env/redis-commander.env
    networks:
      private-net:
        ipv4_address: 172.20.102.8
      public-net:
        ipv4_address: 172.16.102.4
